### ISSUE TITLE
Nodeschool International Day 2016

### ISSUE THREAD

**Issue by jeduan** [nodeschool/mexicocity#11]
Vamos a repetir en el Centro de Cultura Digital el 21 de Mayo de 2016.

Tenemos 10 openings para coaches.

Como en los anteriores, el único requisito para ser coach es hacer antes `javascripting` y/o `learnyounode`.
- [ ] @rogr 
- [x] @kuroganito 
- [x] @elf-pavlik + @ralexrdz 
- [x] @pokaxperia 
- [x] @Ikana 
- [ ] @mottaman85 
- [x] @cube5 
- [x] @SergioMartinezP 
- [x] @Sparragus 
- [ ] 10

**Comment by rog** [comment]
o/

**Comment by kuroganito** [comment]
Yo :)

**Comment by elf-pavlik** [comment]
o/ but I don't speak spanish language :worried: 

maybe also @ralexrdz?

**Comment by ralexrdz** [comment]
yo llevo poco más de un año usando Node y puedo servirle a elf-pablik de traductor. Si se puede, ponganos juntos

**Comment by surielmx** [comment]
Me apunto ;)

**Comment by Ikana** [comment]
Me gustariar se coach

**Comment by Sparragus** [comment]
Hey all! Ya quedan confirmados como coaches para Nodeschool. :D

Es súper imporante que completen los dos workshops que vamos a estar haciendo el sábado: [`javacsripting`](https://github.com/sethvincent/javascripting) y [`learnyounode`](https://github.com/workshopper/learnyounode).

Los pueden instalar usando `npm install --global [javascripting | learnyounode]`.

Les recuerdo que nos vemos este sábado en el [Centro de Cultura Digital](https://www.google.com.mx/maps/place/Centro+de+Cultura+Digital/@19.4231396,-99.1779909,17z/data=!3m1!4b1!4m5!3m4!1s0x85d1ff4ef982846f:0x6dea7372b70b11d8!8m2!3d19.4231346!4d-99.1758022?hl=en) (queda debajo de la Estela de la Luz). La hora de reunión es a las 10:30am. Por favor sean puntual. Los estudiantes llegan muy puntuales y desde el comienzo hay que estar ayudando.

Es útil que traigan su laptop, aunque como coach no es 100% necesario.

Si tienen alguna duda, nos escriben por aca o por [Slack](http://chat.javascriptmx.com/). A Jeduan y a mi nos consiguen en Slack como @jeduan y @richard, respectivamente.

Nos vemos pronto!

**Comment by mottaman85** [comment]
Me gustaría ser coach, aun hay lugar?

**Comment by Sparragus** [comment]
@mottaman85 Sí! :D Solo checa los requisitos en https://github.com/nodeschool/mexicocity/issues/11#issuecomment-219592769 y nos vemos el sábado a las 10:30am en el CCD.

Gracias ^^

**Comment by mottaman85** [comment]
Listo, alla nos vemos dude!

**Comment by kiramishima** [comment]
Como nota, en el anterior nodeschool habia gente que tuvo problemas con los workshoppers por que tenian la ultima version de Node y los workshopppers no funkaban, se soluciono instalandoles node 5.1 , digo por si vuelve a pasar ese caso :P :beers:

**Comment by dsanch3z** [comment]
Puedo entrar? :grin: 
Hay que inscribirse o sólo con completar [javacsripting](https://github.com/sethvincent/javascripting) y [learnyounode](https://github.com/workshopper/learnyounode) es suficiente?

**Comment by Sparragus** [comment]
@cube5 Sí! :D Completa los dos workshop y nos vemos el sábado. :)

**Comment by SergioMartinezP** [comment]
Pues si aún hay lugar, me apunto!

**Comment by jeduan** [comment]
listo, anotados todos!

**Comment by badillosoft** [comment]
Yo no podré apoyarlos porque estoy impartiendo un curso los sábados, pero me gustaría integrarme, les dejo mi twitter y git estaré al pendiente de más eventos. 

twitter: @badillosoft
github: https://github.com/badillosoft/Node
- Si usan mis notas de la certificación de strongloop por fa cítenme 😄

**Comment by jeduan** [comment]
Wut? No, no vamos a usar tus notas. Nodeschool usa curriculum open source.

En [meetup.com](http://meetup.com/javascriptmx) anunciamos todos los eventos que hacemos.
