### ISSUE TITLE
Nodeschool Coaches - sábado 16 de julio de 2016

### ISSUE THREAD

**Issue by Sparragus** [nodeschool/mexicocity#14]
Vamos a repetir en el Centro de Cultura Digital el 16 de julio de 2016.

Tenemos 10 openings para coaches.

Como en los anteriores, el único requisito para ser coach es hacer antes javascripting, learn-sass o learnyoureact.

Puedes ver más información sobre los curso en el website de [Nodeschool](http://nodeschool.io/).
#### Coaches:
- [x] @soujiro27 
- [x] @jeduan
- [x] @marulango 
- [x] @Sparragus 
- [x] @rog 
- [x] @Ikana 
- [x] @pokaxperia 
- [x] @SergioMartinezP 
- [x] @xiam 
- [x] @kouryuu

**Comment by soujiro27** [comment]
Me. Encantaría participar

**Comment by Sparragus** [comment]
Chido @soujiro27! Nos ayudas con tu nombre también? :D Es que solo veo JC.

**Comment by soujiro27** [comment]
juan carlos Ustarroz

**Comment by Sparragus** [comment]
Gracias dude

**Comment by surielmx** [comment]
apoyo en javascripting y learn-sass, y tal vez en learnyoureact

**Comment by SergioMartinezP** [comment]
Apoyo en Javascripting, 

🤔creo que deberé hacer los otros módulos...

**Comment by xiam** [comment]
Puedo ayudar también.

**Comment by kouryuu** [comment]
✋ Me! Pero odio SASS jajaja entonces puedo ayudar en lo demás en mi Github está completo el Javascripting y learnyoureact ... 😄
