### ISSUE TITLE
NodeSchool el sábado 8 feb en Laboratoria CDMX

### ISSUE THREAD

**Issue by lupomontero** [nodeschool/mexicocity#17]
Hola :wave:!

Mi nombre es Lupo Montero. Trabajo en @Laboratoria y también co-organizo LimaJS y NodeSchool en Lima, Perú.

Estamos organizando una NodeSchool en [el espacio de Laboratoria en CDMX](https://goo.gl/maps/JD5WtLb72v5txQh1A) este sábado (8
feb). Yo estoy por acá de paso pero me encantaría conocer a más gente en las comunidades en CDMX y ver cómo podemos echar una mano y participar.

Me encantaría hacer una invitarción abierta y llamado a mentorxs para el sábado. Quién se anima? Acá pueden registrarse.

https://www.eventbrite.com/e/nodeschool-tickets-92940608863

PS: En Lima venimos ya más de año y medio organizando una NodeSchool al mes y me encantaría ver si con el apoyo de Laboratoria y la comunidad que ya existe por acá podemos apuntar a algo parecido en CDMX.

**Comment by holasoymalva** [comment]
Gracias por la propuesta :D les vamos a dar seguimiento . Gracias
