### ISSUE TITLE
Organiza un nodeSchool en tu escuela.

### ISSUE THREAD

**Issue by holasoymalva** [nodeschool/mexicocity#19]
Hey si quieres organizar un WorkShop de nodeSchool eres completamente libre de hacerlo solo recuerda seguir las normas de la comunidad y que este tipo de eventos es para ayudar y aprender :) mucha suerte. Agrega tus propuesta en este issue para darle seguimiento.Estamos para apoyarlos🖖.

**Comment by pablomdd** [comment]
Cuál es el proceso? Se levanta un issue?

**Comment by pablomdd** [comment]
Me latería llevar una Nodeschool a UPIITA y ESCOM en marzo :)

**Comment by holasoymalva** [comment]
Super hay que ir revisando las fechas para ver la posibilidad de conseguir swag :)
