### ISSUE TITLE
Apoyemos el aprendizaje de JS

### ISSUE THREAD

**Issue by holasoymalva** [nodeschool/mexicocity#20]
Hola cracks si quieres hacer tus primeras incursiones en proyectos OpenSource encontraste aqui un lugar donde puedes apoyar sin necesidad de conocimientos muy profundos de desarrollo o programación. Puedes ayudarnos actualizando el listado de comunidades, organizando pequeños labs locales o jams de programacion. Si tienes dudas puedes agregarlas con todo gusto en este issue. Saludos .

**Comment by EduardoPinedaVargas** [comment]
Hola,

Me podrías proporcionar material o algunos tips acerca de como iniciar en el mundo de Node.js
Dejaré la URL de mi perfil de LinkedIn por si gustas contactarme            
https://www.linkedin.com/in/eduardopinedavargas                                                                                                         
De ante mano muchas gracias.

**Comment by holasoymalva** [comment]
Por supuesto @EduardoPinedaVargas te agrego algunos links de interes tanto en español como ingles espero te sean de mucha ayuda. 

[ 👉 Puedes seguir los siguientes consejos 👈](https://www.youtube.com/watch?v=-GB9qKbmGko)

y unirte a los siguientes grupos para obtener retroalimentación y ayuda:
[Facebook Developer Circle: CDMX](https://www.facebook.com/groups/DevCCiudaddeMexico/)
[Facebook Developer Circle: Guadalajara](https://www.facebook.com/groups/DevCGuadalajara/)
[Facebook Developer Circle: Monterrey](https://www.facebook.com/groups/DevCMonterrey/)

y aprender de los siguientes recursos 👇👇👇**MUCHAS SUERTE!!**
https://nodeschool.io/
https://www.w3schools.com/nodejs/
https://learnnode.com/
https://www.tutorialspoint.com/nodejs/index.htm
https://nodejs.org/en/docs/guides/getting-started-guide/
https://nodejs.org/es/docs/
https://developer.mozilla.org/es/docs/Learn/Server-side/Express_Nodejs

**Comment by EduardoPinedaVargas** [comment]
Muchas gracias y ahora si a comenzar en este mundo js
