### ISSUE TITLE
Coaches para international day.

### ISSUE THREAD

**Issue by jeduan** [nodeschool/mexicocity#4]
Necesitamos al menos 6 e idealmente 8-10 coaches para international day. 
Para coachear solo necesitas haber terminado ya sea [javascripting](https://www.npmjs.com/package/javascripting) o [learnyounode](https://www.npmjs.com/package/learnyounode) y tener de 11 am a 3pm disponible el 23 de Mayo para resolver dudas y ayudar a quienes tomaran el curso ese día.
- [x] @jeduan
- [x] @bleedingxedge
- [x] @siedrix
- [x] @unrob
- [x] @juanmcampos 
- [x] @juanjcsr
- [x] @n4utilius
- [x] @pokaxperia 
- [x] @markotom
- [x] @jurasec 
- [x] @ringo22 
- [x] @gandallan
- [x] @tiempor3al
- [x] @martemorfosis 
- [x] @laliux

**Comment by jeduan** [comment]
Anotando a mi y @bleedingxedge. ¿Ustedes podrán ese día? @siedrix @markotom @unrob @rogr @juanjcsr @dudemullet

**Comment by juanmcampos** [comment]
yo

**Comment by juanjcsr** [comment]
+1 Claro! Yo también ando disponible!

**Comment by Dudemullet** [comment]
Lo siento, no podre asistir, tengo una boda ese fin de semana.

**Comment by n4utilius** [comment]
Yo me apunto o///

**Comment by surielmx** [comment]
Listo, Puedo Asistir?????

**Comment by jeduan** [comment]
Cómo @pocaxperia? como coach o como asistente?

**Comment by surielmx** [comment]
Me gustaria como coach. Es necesario tener cierto perfil o pertenecer a un grupo en especifico?, es solo que vi tu tweet y me gust ala idea de ser couch, ademas si tengo tiempo ese dia. Puedo aplicar o necesito tener cierto /nivel/perfil???. Saludos

**Comment by jeduan** [comment]
no, solo haber completado learnyounode y listo.

**Comment by surielmx** [comment]
de hecho complete el de javascripting, necesitas que complete el de learnyounode tambièn?

**Comment by jeduan** [comment]
si te da tiempo, estaría genial, si no te anotamos solo como coach de javascripting

**Comment by surielmx** [comment]
ok, estoy en proceso de learnyounode. Aún asi me apunto para coach, te aviso sobre el status de learnyounode :)

**Comment by markotom** [comment]
yop o/

**Comment by jurasec** [comment]
+1 si aún se puede

**Comment by jeduan** [comment]
Ok, muchas gracias a todos, los agregué a la organización, por favor en cuanto puedan ingresen a este slack para estar en contacto: http://javascriptmx.herokuapp.com

**Comment by eduardosolid** [comment]
yo no puedo :'( tengo ese sábado ocupado, pero gracias por la invitación :)

**Comment by tiempor3al** [comment]
1 more coach here :)

**Comment by jeduan** [comment]
@tiempor3al bien! gracias. Ya estas registrado y en slack?

**Comment by gandhimena** [comment]
Confirmado

2015-05-07 19:03 GMT-05:00 Jeduan Cornejo notifications@github.com:

> Necesitamos al menos 6 e idealmente 8-10 coaches para international day.
> Para coachear solo necesitas haber terminado ya sea javascripting
> https://www.npmjs.com/package/javascripting o learnyounode
> https://www.npmjs.com/package/learnyounode y tener de 11 am a 3pm
> disponible el 23 de Mayo para resolver dudas y ayudar a quienes tomaran el
> curso ese día.
> -  @jeduan https://github.com/jeduan
> -  @bleedingxedge https://github.com/bleedingxedge
> -  @siedrix https://github.com/siedrix
> -  @unrob https://github.com/unrob
> -  @juanmcampos https://github.com/juanmcampos
> -  @juanjcsr https://github.com/juanjcsr
> -  @n4utilius https://github.com/n4utilius
> -  @pokaxperia https://github.com/pokaxperia
> -  @markotom https://github.com/markotom
> -  @jurasec https://github.com/jurasec
> -  @ringo22 https://github.com/ringo22
> -  @gandallan https://github.com/gandallan
> -  @tiempor3al https://github.com/tiempor3al
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/mexicocity/issues/4.

## 
- ```
                                          Lic. Gandhi Mena Salas *
  
                             Diseñador gráfico y publicitario
  
                           Book Mart Digital México
                       gandhimena@gmail.com
  ```

**Comment by martemorfosis** [comment]
Yo le entro mi estimado @jeduan

**Comment by laliux** [comment]
Dicen que más vale que sobre y no que falte, me anoto @jeduan ..

**Comment by jeduan** [comment]
Gracias!

**Comment by jeduan** [comment]
@bleedingxedge @siedrix @unrob @juanmcampos @juanjcsr @n4utilius @pokaxperia @markotom @jurasec @ringo22 @gandallan @tiempor3al @martemorfosis @laliux Ok, pues todo listo. Tengo algunas peticiones para ustedes:
- Traten de hacer hoy los tutoriales para tenerlos frescos
- Lleguen a las 10:45 mañana para poder conocernos
- Si pueden mandenme un correo con Nombre completo, lugar donde trabajan y una foto para incluirlos en la presentación.
- Si tienen, lleven una USB para ayudar a instalar el software. Si pueden bajarlo hoy, es Node.js (0.12) para Windows y OS X y los paquetes de `learnyounode` y `javascripting` de su `node_modules` global.

**Comment by gandhimena** [comment]
Hola Jeduan, los tutoriales los realice esta semana de nuevo para tenerlos
frescos. Te adjunto mis datos.

Nombre: Gandhi Mena Salas
Lugar de trabajo: Editorial Book Mart México
Foto:
[image: Imágenes integradas 1]

Nos vemos mañana. Que tengas un bonito día y un excelente fin de semana.
Saludos

El 22 de mayo de 2015, 18:16, Jeduan Cornejo notifications@github.com
escribió:

> @bleedingxedge https://github.com/bleedingxedge @siedrix
> https://github.com/siedrix @unrob https://github.com/unrob
> @juanmcampos https://github.com/juanmcampos @juanjcsr
> https://github.com/juanjcsr @n4utilius https://github.com/n4utilius
> @pokaxperia https://github.com/pokaxperia @markotom
> https://github.com/markotom @jurasec https://github.com/jurasec
> @ringo22 https://github.com/ringo22 @gandallan
> https://github.com/gandallan @tiempor3al https://github.com/tiempor3al
> @martemorfosis https://github.com/martemorfosis @laliux
> https://github.com/laliux Ok, pues todo listo. Tengo algunas peticiones
> para ustedes:
> - Traten de hacer hoy los tutoriales para tenerlos frescos
> - Lleguen a las 10:45 mañana para poder conocernos
> - Si pueden manden un correo con Nombre completo, lugar donde trabajan
>   y una foto para incluirlos en la presentación.
> - Si tienen, lleven una USB para ayudar a instalar el software. Si
>   pueden bajarlo hoy, es Node.js (0.12) para Windows y OS X y los paquetes de
>   learnyounode y javascripting de su node_modules global.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nodeschool/mexicocity/issues/4#issuecomment-104796833
> .

## 
- ```
                                          Lic. Gandhi Mena Salas *
  
                             Diseñador gráfico y publicitario
  
                           Book Mart Digital México
                       gandhimena@gmail.com
  ```
