### ISSUE TITLE
Coaches para Campus Party

### ISSUE THREAD

**Issue by jeduan** [nodeschool/mexicocity#5]
Necesitamos al menos 4 e idealmente 6-8 coaches para #CPMX6.
Para coachear solo necesitas haber terminado ya sea [javascripting](http://npmjs.com/javascripting) o [learnyounode](http://npmjs.com/learnyounode) y tener de 10 pm en adelante disponible el 23 de Julio para resolver dudas y ayudar a quienes tomaran el curso ese día.
- [x] @jeduan
- [x] @siedrix
- [x] @salvadorbfm
- [x] @jurasec
- [x] @sergiomartinezp
- [x] @pokaxperia 
- [ ]
- [ ]

**Comment by jurasec** [comment]
+1

**Comment by kiramishima** [comment]
+1

**Comment by CarlGearsTech** [comment]
En codigo de conducta: 

Si un miembro de la comunidad mostrara cualquier conducta abusiva, los organizadores de Nodeschool Ciudad de México pueden tomar cualquier acción que crean apropiada, incluyendo avisar a los que ofendan o expulsarlos de la comunidad. 

Mejor: 
Si un miembro de la comunidad mostrara cualquier conducta abusiva, los organizadores de Nodeschool Ciudad de México pueden tomar cualquier acción que crean apropiada, incluyendo llamada de atención o expulsarlo("s" estamos hablando de una sola persona ¿cierto?) de la comunidad.
