### ISSUE TITLE
Mejor Redacción :D

### ISSUE THREAD

**Issue by CarlGearsTech** [nodeschool/mexicocity#6]
En codigo de conducta:

Si un miembro de la comunidad mostrara cualquier conducta abusiva, los organizadores de Nodeschool Ciudad de México pueden tomar cualquier acción que crean apropiada, incluyendo avisar a los que ofendan o expulsarlos de la comunidad.

Mejor:
Si un miembro de la comunidad mostrara cualquier conducta abusiva, los organizadores de Nodeschool Ciudad de México pueden tomar cualquier acción que crean apropiada, incluyendo llamada de atención o expulsarlo("s" estamos hablando de una sola persona ¿cierto?) de la comunidad.

https://github.com/nodeschool/mexicocity/blob/master/codeofconduct.md

**Comment by jeduan** [comment]
Gracias por tu colaboración @CharlieHdzMx
