### ISSUE TITLE
Próximo Nodeschool

### ISSUE THREAD

**Issue by rog** [nodeschool/mexicocity#8]
En febrero del año pasado fue el ultimo Nodeschool Mexico City (que no haya sido el Nodeschool Day).
Creo es tiempo de organizar uno nuevo.
El próximo Nodeschool Day es el 21 de Mayo, me parece que podemos crear un nuevo capitulo de Nodeschool en Marzo. ¿que les parece la idea? ¿estan disponibles?

**Comment by n4utilius** [comment]
pos me apunto o/

**Comment by ringo22** [comment]
Yo también !!!

**Comment by juanmcampos** [comment]
Yo igual :) me apunto

**Comment by markotom** [comment]
Cuenten conmigo también :grinning:

**Comment by jeduan** [comment]
Muchas gracias a todos. Parece que por fin cerramos el venue. Abrí #9 para registrar coaches. ¿Me confirman si pueden por allá? @rogr @n4utilius @ringo22 @juanmcampos @markotom
