### ISSUE TITLE
Nodeschool Marzo 2016

### ISSUE THREAD

**Issue by jeduan** [nodeschool/mexicocity#9]
Ya tenemos el venue, y va a ser un sábado de Marzo de 10 AM a 3 PM (les confirmo cuál en este mismo issue mañana).

Tenemos 8 openings para coaches y 1 opening para alguien que nos ayude como core organizer que nos ayude con tareas de PR y difusión pre-evento.

Como en los anteriores, el único requisito para ser coach es hacer antes `javascripting` y/o `learnyounode` y para lo demás unas 8 horas en las semanas de aquí a que pase el evento.
- [x] @rogr [org]
- [x] @juanmcampos 
- [x] @carlangueitor
- [x] @pateketrueke
- [x] @marulango 
- [x] @pokaxperia
- [x] @MarcoAguayoG1915 
- [x] @vansters-dev
- [x] @kiramishima 
- [x] @n4utilius 
- [x] @thinkMX

**Comment by juanmcampos** [comment]
:+1:  genial

**Comment by rog** [comment]
Me anoto como organizer.
Ademas de `javascripting` y `learnyounode` estaba pensansando que podemos dar el de `ES6`.
Que te parece la idea @jeduan?

**Comment by jeduan** [comment]
Me late!

**Comment by Carlangueitor** [comment]
Yo me apunto, aunque no me he chutado todavía ninguno de esos :stuck_out_tongue:

**Comment by pateketrueke** [comment]
Suena chingón, ¿puedo? :beers:

**Comment by drochag** [comment]
yo también me apunto :smiley_cat: pero igual que @Carlangueitor … no he hecho esos :astonished:

**Comment by jeduan** [comment]
@Carlangueitor @DanMMX pues tienen todavía tiempo para hacerlos! `npm install -g javascripting` y `npm install -g learnyounode`

**Comment by jeduan** [comment]
Por cierto, todos, tengo que mandar una Semblanza del ustedes al venue. ¿Me escriben a mi correo con cosas como Donde trabajan, años de usar node/escribir software, foto, etc?

**Comment by pateketrueke** [comment]
Oye @jeduan ¿neta hay que hacer lo de `javascripting` y `learnyounode` para ser coach? D:

**Comment by juanmcampos** [comment]
@jeduan claro pero perdí tu correo

**Comment by Carlangueitor** [comment]
Andale @pateketrueke ni que fuera mucho tiempo :stuck_out_tongue:

**Comment by pateketrueke** [comment]
¿Y si ya renuncié a mi trabajo qué pongo en la semblanza? D:

**Comment by Sparragus** [comment]
Proyectos que hayas hecho o en los que hayas trabajado está bien.

Richard Kaufman

**Comment by DanMMX** [comment]
a qué correo @jeduan ?

**Comment by jeduan** [comment]
hola@jeduan.com

**Comment by Zenntro** [comment]
@jeduan Yo también me anoto

**Comment by kiramishima** [comment]
@jeduan me apunto :beer: XD aunque nunca hice el de javascripting solo el de learnyounode :smile: , eso si tuve mis 2 stickers del año pasado XD

**Comment by marulango** [comment]
YOQUIERO YO ME APUNTO :dancer:

**Comment by juanmcampos** [comment]
@jeduan @MarcoAguayoG1915  ya completo los dos :)

**Comment by rog** [comment]
¿Ya hay mas info del venue/fecha, necesitamos algo mas aparte de los tres coaches restantes?

**Comment by jeduan** [comment]
LISTO! 12 de Marzo en Centro de Cultura Digital (https://es-la.facebook.com/CentroCulturaDigital/).

Hay un tema: Necesito la info de todos los coaches ya! Los que falten por favor mándenmela lo antes posible.

**Comment by jeduan** [comment]
@MarcoAguayoG1915 ¿Estas en el slack? Si no, entra cuando tengas un chance para agregarte al grupo: http://chat.javascriptmx.com

**Comment by kiramishima** [comment]
T_T sigo sin aparecer en el listado XD T_T es por que uso Go XD

**Comment by jeduan** [comment]
@kiramishima Me perdonas? Fallé en el multitasking

**Comment by ghost** [comment]
hola @jeduan hay lugares todavía para ser coach de javascript? Si si tienes, anótame!
Te mando mis datos a tu correo y si no pues para la próxima =D

**Comment by kiramishima** [comment]
@jeduan  yo solo decía XP , nos vemos en el nodeschool y después en el chelajs XD

**Comment by Zenntro** [comment]
@jeduan acabo de registrarme en el slack ;)

**Comment by n4utilius** [comment]
recién me dí cuenta de que ya estaban cerrando detalles ¿todavía hay lugares para couch?

**Comment by jeduan** [comment]
@thinkMX estás en el slack?

**Comment by bialikover** [comment]
creo que llegue muy tarde jaja, aún se puede entrar como coach?
